-- Replace the placeholder quiz bank with the real questions supplied for the program (3 per module,
-- 4 options each, bilingual). No real ambassador had taken a quiz yet, so this is a clean swap.
delete from public.unicef_quiz_questions;

insert into public.unicef_quiz_questions (id, module_id, sort, question_en, question_hy, options, correct) values

-- Module 1: Climate Change: A Scientific Overview
('m1q1', 'm1', 1,
 'What is the main cause of modern climate change?',
 'Ո՞րն է ժամանակակից կլիմայի փոփոխության հիմնական պատճառը:',
 '[{"key":"a","en":"Natural changes in solar activity","hy":"Արեգակնային ակտիվության բնական փոփոխությունները"},
   {"key":"b","en":"Greenhouse gas emissions from human activities","hy":"Մարդու գործունեության հետևանքով ջերմոցային գազերի արտանետումները"},
   {"key":"c","en":"Volcanic eruptions","hy":"Հրաբխային ժայթքումները"},
   {"key":"d","en":"Natural cycles of ocean currents","hy":"Օվկիանոսային հոսանքների բնական ցիկլերը"}]', '{b}'),
('m1q2', 'm1', 2,
 'Why is it vitally important to limit global warming to 1.5°C?',
 'Ինչո՞ւ է կենսականորեն կարևոր գլոբալ տաքացումը սահմանափակել 1.5°C-ով:',
 '[{"key":"a","en":"It will prevent any kind of weather disaster","hy":"Դա կկանխի ցանկացած տեսակի եղանակային աղետ"},
   {"key":"b","en":"It will significantly reduce the risks of irreversible ecological and human losses","hy":"Այն էապես կնվազեցնի անդառնալի էկոլոգիական և մարդկային կորուստների ռիսկերը"},
   {"key":"c","en":"It will lead to a new ice age","hy":"Դա կհանգեցնի նոր սառցե դարաշրջանի"},
   {"key":"d","en":"This limit is purely symbolic","hy":"Այդ սահմանաչափը միայն խորհրդանշական բնույթ է կրում"}]', '{b}'),
('m1q3', 'm1', 3,
 'What is a fair approach to climate action on a global level?',
 'Ինչպիսի՞ն է կլիմայական գործողությունների արդարացի մոտեցումը համաշխարհային մակարդակում:',
 '[{"key":"a","en":"Only developing countries should cut emissions","hy":"Միայն զարգացող երկրները պետք է կրճատեն արտանետումները"},
   {"key":"b","en":"Everyone should bear the exact same financial burden regardless of capacity","hy":"Յուրաքանչյուրը պետք է կրի միատեսակ ֆինանսական բեռ՝ անկախ հնարավորություններից"},
   {"key":"c","en":"Responsibility should be common but differentiated, based on historical emissions and economic capacity","hy":"Պատասխանատվությունը պետք է լինի ընդհանուր, բայց տարբերակված՝ հիմնված պատմական արտանետումների և տնտեսական հնարավորությունների վրա"},
   {"key":"d","en":"Climate change should not concern developed countries","hy":"Կլիմայի փոփոխությունը չպետք է անհանգստացնի զարգացած երկրներին"}]', '{c}'),

-- Module 2: Biodiversity: What Do We Know About It
('m2q1', 'm2', 1,
 'What does biodiversity represent?',
 'Ի՞նչ է իրենից ներկայացնում կենսաբազմազանությունը:',
 '[{"key":"a","en":"Only forest ecosystems","hy":"Միայն անտառային էկոհամակարգերը"},
   {"key":"b","en":"Genetic, species, and ecosystem diversity around the world","hy":"Գենետիկական, տեսակային և էկոհամակարգային բազմազանությունն ամբողջ աշխարհում"},
   {"key":"c","en":"Only endangered animal species","hy":"Միայն վտանգված կենդանիների տեսակները"},
   {"key":"d","en":"Only animals and plants living in urban conditions","hy":"Միայն քաղաքային պայմաններում ապրող կենդանիներն ու բույսերը"}]', '{b}'),
('m2q2', 'm2', 2,
 'Why is biodiversity loss dangerous for humanity?',
 'Ինչո՞ւ է կենսաբազմազանության կորուստը վտանգավոր մարդկության համար:',
 '[{"key":"a","en":"It disrupts ecosystem services such as clean air, water, and food security","hy":"Այն խաթարում է էկոհամակարգային ծառայությունները, ինչպիսիք են մաքուր օդը, ջուրը և պարենային անվտանգությունը"},
   {"key":"b","en":"It reduces the number of zoo visitors","hy":"Այն նվազեցնում է կենդանաբանական այգիների այցելուների թիվը"},
   {"key":"c","en":"It leads to urban overpopulation","hy":"Այն հանգեցնում է քաղաքների գերբնակեցման"},
   {"key":"d","en":"It does not affect human health in any way","hy":"Այն որևէ կերպ չի ազդում մարդկանց առողջության վրա"}]', '{a}'),
('m2q3', 'm2', 3,
 'Which value approach is most ethical and sustainable in nature conservation?',
 'Բնության պահպանության հարցում ո՞ր արժեքային մոտեցումն է առավել էթիկական և կայուն:',
 '[{"key":"a","en":"Nature exists solely to satisfy human needs","hy":"Բնությունը գոյություն ունի բացառապես մարդկանց կարիքները բավարարելու համար"},
   {"key":"b","en":"All species have an intrinsic right to exist, regardless of their economic value to humans","hy":"Բոլոր տեսակներն ունեն գոյության ներքին իրավունք՝ անկախ մարդու համար դրանց տնտեսական արժեքից"},
   {"key":"c","en":"Conservation should only be done when it is profitable for the economy","hy":"Պահպանությունը պետք է իրականացվի միայն այն ժամանակ, երբ դա շահութաբեր է տնտեսության համար"},
   {"key":"d","en":"Technologies can always fully replace destroyed ecosystems","hy":"Տեխնոլոգիաները միշտ կարող են ամբողջությամբ փոխարինել ոչնչացված էկոհամակարգերին"}]', '{b}'),

-- Module 3: Pollution, Waste and Circular Economy
('m3q1', 'm3', 1,
 'What is the main principle of a circular economy?',
 'Ո՞րն է շրջանաձև տնտեսության հիմնական սկզբունքը:',
 '[{"key":"a","en":"Take, make, dispose","hy":"Արտադրել, օգտագործել, դեն նետել"},
   {"key":"b","en":"Minimize waste by keeping materials and resources in circulation for as long as possible","hy":"Նվազագույնի հասցնել թափոնները՝ նյութերն ու ռեսուրսները հնարավորինս երկար պահելով շրջանառության մեջ"},
   {"key":"c","en":"Increase single-use plastic consumption to boost production","hy":"Ավելացնել պլաստիկի մեկանգամյա օգտագործումը՝ արտադրությունը խթանելու համար"},
   {"key":"d","en":"Make incineration the primary and only method of waste management","hy":"Աղբայրումը դարձնել թափոնների կառավարման հիմնական և միակ միջոց"}]', '{b}'),
('m3q2', 'm3', 2,
 'What does Extended Producer Responsibility (EPR) imply?',
 'Ի՞նչ է ենթադրում Արտադրողի ընդլայնված պատասխանատվությունը (ԱԸՊ):',
 '[{"key":"a","en":"Consumers pay the full cost of waste recycling","hy":"Սպառողներն են վճարում թափոնների վերամշակման ողջ ծախսը"},
   {"key":"b","en":"Producers bear financial and/or physical responsibility for the entire life cycle of their product, including its disposal","hy":"Արտադրողները ֆինանսական և/կամ ֆիզիկական պատասխանատվություն են կրում իրենց ապրանքի ամբողջ կյանքի ցիկլի, ներառյալ՝ դրա հեռացման համար"},
   {"key":"c","en":"Waste collection and sorting is exclusively the problem of local municipalities","hy":"Թափոնների հավաքագրումն ու տեսակավորումը բացառապես տեղական ինքնակառավարման մարմինների խնդիրն է"},
   {"key":"d","en":"The government bans the production of packaged goods","hy":"Կառավարությունն արգելում է փաթեթավորմամբ ապրանքների արտադրությունը"}]', '{b}'),
('m3q3', 'm3', 3,
 'What is the most mindful attitude in solving the waste problem?',
 'Ո՞րն է ամենագիտակից մոտեցումը թափոնների խնդրի լուծման գործում:',
 '[{"key":"a","en":"Focus only on increasing the number of landfills","hy":"Կենտրոնանալ միայն աղբավայրերի քանակի ավելացման վրա"},
   {"key":"b","en":"Start with reducing consumption and making conscious purchases before thinking about recycling","hy":"Սկսել սպառման կրճատումից (reduce) և գիտակից գնումներից՝ նախքան վերամշակման (recycle) մասին մտածելը"},
   {"key":"c","en":"Wait until the government creates a perfect system","hy":"Սպասել, մինչև կառավարությունը կստեղծի կատարյալ համակարգ"},
   {"key":"d","en":"Rely only on annual volunteer clean-up days","hy":"Ապավինել միայն տարեկան կամավորական շաբաթօրյակներին"}]', '{b}'),

-- Module 4: Environmental Policy Making and Advocacy
('m4q1', 'm4', 1,
 'What is the main objective of environmental protection policy?',
 'Ի՞նչ հիմնական նպատակ է հետապնդում շրջակա միջավայրի պահպանության քաղաքականությունը:',
 '[{"key":"a","en":"To restrict any kind of economic activity","hy":"Սահմանափակել ցանկացած տեսակի տնտեսական գործունեություն"},
   {"key":"b","en":"To regulate human-nature interaction by promoting sustainable development and wise resource management","hy":"Կարգավորել մարդ-բնություն փոխազդեցությունը՝ խթանելով կայուն զարգացումն ու ռեսուրսների խելամիտ կառավարումը"},
   {"key":"c","en":"To promote the global use of fossil fuels","hy":"Խթանել հանածո վառելիքի գլոբալ օգտագործումը"},
   {"key":"d","en":"To create only reserves without considering societal needs","hy":"Ստեղծել միայն արգելոցներ՝ առանց հաշվի առնելու հասարակության կարիքները"}]', '{b}'),
('m4q2', 'm4', 2,
 'The Paris Agreement is a prime example of international policy in which field?',
 'Փարիզյան համաձայնագիրը ո՞ր ոլորտի միջազգային քաղաքականության վառ օրինակ է:',
 '[{"key":"a","en":"International trade agreements","hy":"Միջազգային առևտրի պայմանագրերի"},
   {"key":"b","en":"Peaceful space exploration","hy":"Տիեզերքի խաղաղ նպատակներով հետազոտության"},
   {"key":"c","en":"Climate change mitigation and adaptation","hy":"Կլիմայի փոփոխության մեղմացման և հարմարվողականության"},
   {"key":"d","en":"Banning the export of plastic waste","hy":"Պլաստիկ թափոնների արտահանման արգելքի"}]', '{c}'),
('m4q3', 'm4', 3,
 'Which value is central when developing effective and sustainable environmental policy?',
 'Արդյունավետ և կայուն բնապահպանական քաղաքականություն մշակելիս ո՞ր արժեքն է առանցքային:',
 '[{"key":"a","en":"Making decisions exclusively behind closed doors","hy":"Որոշումներ կայացնել բացառապես փակ դռների հետևում"},
   {"key":"b","en":"Ensuring inclusivity and a participatory process by listening to the voices of local communities, scientists, and youth","hy":"Ապահովել ներառականություն և մասնակցային գործընթաց՝ լսելով տեղական համայնքների, գիտնականների և երիտասարդների ձայնը"},
   {"key":"c","en":"Ignoring scientific arguments in favor of short-term political or economic profit","hy":"Անտեսել գիտական փաստարկները՝ հօգուտ կարճաժամկետ քաղաքական կամ տնտեսական շահույթի"},
   {"key":"d","en":"Considering only the interests of large industrial corporations","hy":"Հաշվի առնել միայն խոշոր արդյունաբերական կորպորացիաների շահերը"}]', '{b}'),

-- Module 5: Public Awareness and Civic Engagement: A Youth Context
('m5q1', 'm5', 1,
 'Which of the following is an example of active civic engagement in the environmental field?',
 'Նշվածներից ո՞րն է բնապահպանական ոլորտում քաղաքացիական ակտիվ ներգրավվածության օրինակ:',
 '[{"key":"a","en":"Watching nature documentaries without taking action","hy":"Բնության մասին վավերագրական ֆիլմեր դիտելն առանց գործողության"},
   {"key":"b","en":"Participating and voting in public hearings against the construction in urban green spaces","hy":"Քաղաքային կանաչ տարածքների կառուցապատման դեմ հանրային լսումներին մասնակցելն ու քվեարկելը"},
   {"key":"c","en":"Posting only personal leisure pictures on social networks","hy":"Սոցիալական ցանցերում միայն անձնական ժամանցի նկարներ հրապարակելը"},
   {"key":"d","en":"Showing indifference to local ecological issues","hy":"Անտարբերություն ցուցաբերելը տեղական էկոլոգիական խնդիրների նկատմամբ"}]', '{b}'),
('m5q2', 'm5', 2,
 'Why is the youth voice important in international climate processes (e.g., in LCOY or COP conferences)?',
 'Ինչո՞ւ է երիտասարդների ձայնը կարևոր միջազգային կլիմայական գործընթացներում (օրինակ՝ LCOY կամ COP համաժողովներում):',
 '[{"key":"a","en":"It is simply a formal requirement by international organizations","hy":"Դա պարզապես ձևական պահանջ է միջազգային կազմակերպությունների կողմից"},
   {"key":"b","en":"Because youth have more free time to attend events","hy":"Որովհետև երիտասարդներն ունեն ավելի շատ ազատ ժամանակ միջոցառումներին մասնակցելու համար"},
   {"key":"c","en":"Youth represent the interests of future generations and often bring ambitious, innovative, and out-of-the-box solutions","hy":"Երիտասարդները ներկայացնում են ապագա սերունդների շահերը և հաճախ բերում են հավակնոտ, նորարարական և ոչ ստանդարտ լուծումներ"},
   {"key":"d","en":"Youth should only participate in logistical work","hy":"Երիտասարդները պետք է մասնակցեն միայն լոգիստիկ աշխատանքներին"}]', '{c}'),
('m5q3', 'm5', 3,
 'What is the main driving force behind effective public awareness on climate and environmental topics?',
 'Ո՞րն է կլիմայի և բնապահպանության թեմաներով արդյունավետ հանրային իրազեկման հիմնական շարժիչ ուժը:',
 '[{"key":"a","en":"Constantly inducing fear and despair about the future (eco-anxiety) in people","hy":"Մարդկանց մոտ անընդհատ վախ առաջացնելն ու ապագայի հանդեպ հուսահատեցնելը (էկո-տագնապ)"},
   {"key":"b","en":"Exclusively using complex academic terms to impress the audience","hy":"Բացառապես բարդ ակադեմիական տերմիններ օգտագործելը՝ լսարանին տպավորելու համար"},
   {"key":"c","en":"Building empathy and driving people towards clear, everyday actionable steps","hy":"Էմպաթիա (կարեկցանք) ձևավորելը և մարդկանց հստակ, առօրյայում կիրառելի գործողությունների մղելը"},
   {"key":"d","en":"Blaming individual people for global systemic crises","hy":"Մեղադրել առանձին անհատներին համաշխարհային համակարգային ճգնաժամերի համար"}]', '{c}');
